#pragma once
#define BLACK 0
#define BLUE           FOREGROUND_BLUE
#define GREEN          FOREGROUND_GREEN
#define RED            FOREGROUND_RED
#define YELLOW         (FOREGROUND_RED | FOREGROUND_GREEN)
#define MAGENTA        (FOREGROUND_BLUE | FOREGROUND_RED)
#define CYAN           (FOREGROUND_BLUE | FOREGROUND_GREEN)
#define WHITE          (FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_RED)

#define INTENSITY_BLACK    FOREGROUND_INTENSITY
#define INTENSITY_BLUE     (FOREGROUND_BLUE | FOREGROUND_INTENSITY)
#define INTENSITY_GREEN    (FOREGROUND_GREEN | FOREGROUND_INTENSITY)
#define INTENSITY_RED      (FOREGROUND_RED | FOREGROUND_INTENSITY)
#define INTENSITY_YELLOW   (FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY)
#define INTENSITY_MAGENTA  (FOREGROUND_BLUE | FOREGROUND_RED | FOREGROUND_INTENSITY)
#define INTENSITY_CYAN     (FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY)
#define INTENSITY_WHITE    (FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_RED | FOREGROUND_INTENSITY)


enum
{
	E_MENU,
	E_GAME,
	E_STATE_MAX
};
